### ISSUE TITLE
After picking source rig, its not showing UI for mapping

### ISSUE THREAD

**Issue by lalamax3d** [Mwni/blender-animation-retargeting#1]
Hi, i am using blender 2.82a.
i just downloaded and installed and it load correctly ( without any error )
my character is rigify rig and source is mixamo fbx loaded. after picking source, it simply doesn't show UI for mapping as you have shown in your readme.md
thanks for sharing code. regard,haseeb

**Comment by Mwni** [comment]
This is fixed now. Thanks for the report.

**Comment by lalamax3d** [comment]
thanks, confirmed, working for me.
