### ISSUE TITLE
Is the add-on compatible with 2.9?

### ISSUE THREAD

**Issue by jordanbharris** [Mwni/blender-animation-retargeting#10]
Hello,
Is your tool not compatible with Blender 2.9 or am I not installing it correctly? I get this error when trying to enable it: 

Traceback (most recent call last):
  File "C:\Program Files\Blender Foundation\Blender 2.90\2.90\scripts\modules\addon_utils.py", line 351, in enable
    mod = __import__(module_name)
  File "C:\Users\jbh_work\AppData\Roaming\Blender Foundation\Blender\2.90\scripts\addons\addon.py", line 16, in <module>
    from . import data
ImportError: attempted relative import with no known parent package

![add_on_error](https://user-images.githubusercontent.com/64159311/94735378-8549ae00-031f-11eb-98ac-425e06ca963f.PNG)

Thanks!

**Comment by Mwni** [comment]
Did you install it like described in the docs?

**Comment by jordanbharris** [comment]
Ahh, I had already unzipped the file, didn't realize it works/loads from zip. I am new to Blender 
It has been enabled, I will give it a test drive. 
Thank you!
