### ISSUE TITLE
No Rest Alignment in 2.92

### ISSUE THREAD

**Issue by amarillosebas** [Mwni/blender-animation-retargeting#13]
After aligning the target armature, pressing apply seems to do nothing. No errors thrown.

![image](https://user-images.githubusercontent.com/5789040/115298899-b2c34100-a123-11eb-8e95-fd1b69a2ba97.png)

![image](https://user-images.githubusercontent.com/5789040/115298952-c53d7a80-a123-11eb-81b8-4eb623b80d03.png)

**Comment by Mwni** [comment]
Yes this is a known issue that I still haven't come around to fix. If there is no change in the pose, the addon assumes this step has not been completed. Just rotate any bone 0.0001 degrees.

**Comment by Mwni** [comment]
Fixed by https://github.com/Mwni/blender-animation-retargeting/commit/24ab1026b8a4fc5c0d5b1b104a595c7f81f802ee.
