### ISSUE TITLE
Add option to bake keyframes for mapped bones only?

### ISSUE THREAD

**Issue by ogiesen** [Mwni/blender-animation-retargeting#16]
I was wondering why the .blend-files I was using to bake the new retargeted actions into were getting so ridiculously large (>1 GB for 5 of the simplest Mixamo animations imported for testing, all only between 120 and 300 frames in length) - until I figured out that the Bake function had apparently created keyframes for every single bone in the armature even though I had only mapped 61...

The rig I was working with at the time has several hundred bones in it (it's a Rigify rig extended with lots of extra stuff - but even a regular Rigify rig including a facial rig will also already have a ton of bones you would typically not map - most notably the facial bones).

After manually purging all the unnecessary bone channels I got the file down to a measly 66MB. However, that is not really a feasible approach (it took me over an hour to manually clean up those 5 actions).

Would it be possible to optionally only bake keyframes for the bones that have actually been mapped? (which is what I had expected to happen - though I can certainly envision situations where it might come in handy to automatically bake additional bones at the same time, e.g. wiggle mechanics - so by all means keep this optional)

**Comment by tokitoki22** [comment]
I think the add on offer bake function do same thing as blender bake function. with auto apply option setting.

So if you use blender animation baking command (from blender menu), you can select option, which only bake keys for selected bones..

About  2.92 there was bug about baking animation, but 2.93 recent beta, and 3.00 already resolve the issue, or 2.83 work stable.

**Comment by Mwni** [comment]
@tokitoki22 is correct, the addon simply invokes Blender's built-in bake. Feel free to reopen if you still have an issue with this.
