### ISSUE TITLE
Source Pose resets when trying to set up rest alignment

### ISSUE THREAD

**Issue by KiaArmani** [Mwni/blender-animation-retargeting#2]
I am currently trying to retarget an exported BVH animation from Rokoko Studio to the Unreal Engine Skeleton. For this, I exported the Unreal Mannequin and imported it into Blender as FBX and then imported the BVH (which has no mesh), set up the bone mapping & ended up with this.

![grafik](https://user-images.githubusercontent.com/3679543/81486304-1ffffe00-9254-11ea-9be3-42fb43c6d0da.png)

With the problem being that as I soon as I hit "Set Up" I am greeted with a "resetted" looking source pose.

![grafik](https://user-images.githubusercontent.com/3679543/81486323-3c039f80-9254-11ea-91c9-d2048d86976a.png)

I have attached the models and my bone mapping to this issue.

[blender-anim-retargeting.zip](https://github.com/Mwni/blender-animation-retargeting/files/4604678/blender-anim-retargeting.zip)

**Comment by Mwni** [comment]
Upon clicking on "set up", the source armature is supposed to go into the rest pose. The point of that is that you then adjust the source's pose to match the target, then save it by clicking apply, so the addon can calculate the delta transforms. Reading your post it seems that you have given the source a pose beforehand, what were the intentions of that?

**Comment by KiaArmani** [comment]
Assuming you mean the poses in the Scene Collection view, those existing upon import already for both.

**Comment by Mehdianim** [comment]
I have the same exact issue as described above. BVH files come with the weird rest pose where all the bones point down. I already had my source posed correctly before. hitting the setup button. What would really help would be to say "Use current poses as rest" or something.

**Comment by schroef** [comment]
I also see this happening. The source actually goes into rest pose and my target as well. Hitting apply it keeps showing no rest pose, i dont see any error output.

**Comment by Mwni** [comment]
@schroef I stated that you need to adjust the pose of the target armature, never the source. The said pose alignment must be done directly after clicking "Set up"; If done outside of this mode, the addon will not interpret the poses correctly. If you hit "Apply" without making any changes, the addon mistakingly assumes this step has not been completed, so until I have fixed this, rotate one bone ever so slightly ;)

**Comment by schroef** [comment]
Perhaps I didn't get this line correct, but to me it sounded like we needed to adjust the source


It was a couple responses back upwards
"The point of that is that you then adjust the source's pose to match the target, then save it by clicking apply, s"

**Comment by Mwni** [comment]
Yes, that was incorrect, my bad.

**Comment by Mwni** [comment]
Closing as it seems stale. Please reopen if it is not resolved.
