### ISSUE TITLE
getting the animation baked results in a error

### ISSUE THREAD

**Issue by MataPuelc0s** [Mwni/blender-animation-retargeting#23]
Hi, I followed all the steps on a couple of armatures perfectly matching, the source armature have a animation linked, target armature follows. when I try to bake I had this:
![image](https://user-images.githubusercontent.com/56326550/188692069-37bfa6f2-243d-41ba-a7f1-5e50a66e12fe.png)
what could be wrong?

**Comment by Mwni** [comment]
This should have been fixed by https://github.com/Mwni/blender-animation-retargeting/commit/3becc2454a7b9efa6cc5d74b30b68861a90bbe21. Are you sure you are running the latest version?

**Comment by MataPuelc0s** [comment]
oh, my bad, since the version is 1.0 at latest too, didn't know that updating could solve it. thanks
