### ISSUE TITLE
New Bone Mapping Controls

### ISSUE THREAD

**Issue by wikid24** [Mwni/blender-animation-retargeting#28]
Hi there @Mwni , I added some controls to my [FFXIV MMD Tools Helper](https://github.com/wikid24/ffxiv_mmd_tools_helper) addon today to automate populating the bone mapping and make it easier for users of your addon to use. A lot of the time the bones names are in Japanese or Chinese on the source armature, while the target armature is (usually) in English, so typing in bone names into the mapping table is really hard to do. Making it easier to select a bone on the viewport and add it as a source bone or target bone would really go a long way for users.

I thought you might find some of it useful to integrate some additional controls of the mapping table into your own addon (then I can remove them from mine) :)

- addon operator code: https://github.com/wikid24/ffxiv_mmd_tools_helper/blob/master/ffxiv_mmd_tools_helper/bone_retargeting_addon.py
- UI panel code: https://github.com/wikid24/ffxiv_mmd_tools_helper/blob/master/ffxiv_mmd_tools_helper/panels_retargeting_addon.py

![image](https://github.com/wikid24/ffxiv_mmd_tools_helper/assets/19479648/a4e7323c-fdef-4ee5-99be-20f5c1fae979)

Video of it in action:

https://github.com/wikid24/ffxiv_mmd_tools_helper/assets/19479648/a47f58b8-e930-468f-8e79-aa36f1f77b86

Cheers!

**Comment by Mwni** [comment]
Hey @wikid24, I apologize for missing your post. Thank you for sharing this. Bone guessing had been implemented in the meantime.
