### ISSUE TITLE
Option to have the retargeted animation over another animation

### ISSUE THREAD

**Issue by RaphaelDrewBoltman** [Mwni/blender-animation-retargeting#31]
Hello! I want to firstly say that this tool is phenomenal as I've been looking for an accurate retargeting tool since the start of this mini-project I am working and helping in.
Although the question I want to pull is the following:
Is there any way to have the retargeted animation over another animation from its target?
In my case, I had the source and target, both with animations as the source has no hand animations. If I enable drivers it will look just like how I want, with the hands and quills from the target's animation, and the body, arms and legs from the source's animation:
https://github.com/Mwni/blender-animation-retargeting/assets/50070802/7a97aabd-2e1a-4955-ae14-325fb24073e8

After I Bake the source's animation, the hands and quills will be posed from the frame I stopped, leaving me with source's animation retargeted only and with no target's animation from the quills (which I didn't mapped them) and hands (there are none as seen from the previous video too):
https://github.com/Mwni/blender-animation-retargeting/assets/50070802/b7c823af-42a9-408e-a9e2-4020cbdd30ce

I will gladly wait for a response and possible solution, as I'm near the finish line for this little project and to end retargeting the animations I have left still.
Thank you for reading and apologies for any inconvenience!

**Comment by Mwni** [comment]
> If I enable drivers it will look just like how I want

If it looks just like you want, you might want to try baking the animation manually with "visual keying" enabled.

**Comment by RaphaelDrewBoltman** [comment]
I might got a silly workaround by activating it and selecting all the bones I needed, copied and pasted after baking the retargeted animation. But at least it worked just fine with both.
Thank you for replying and helping!
