### ISSUE TITLE
Retargeting Addon stuck

### ISSUE THREAD

**Issue by wannoo** [Mwni/blender-animation-retargeting#36]
Upon selecting a Source Animation the addon gets stuck and I am unable to deselect source. I reinstalled the addon 2 times and the issue persists. 
![2024-06-12 16_45_17-_ TBSE + TBSE-X + IVCS Blender Kit 1_3mods  D__Gen2-Gen3_Converter_Body ressourc](https://github.com/Mwni/blender-animation-retargeting/assets/139268851/412c1c5f-e68c-4a83-a6b1-fbf95247bc71)

**Comment by mtpiercey** [comment]
For future reference, if anyone else experiences this issue (like I did today), I think I found a workaround.
Try running this script, after selecting the Source Armature that got stuck in this state:

```python
import bpy

selected = bpy.context.selected_objects

bpy.context.object.retargeting_context.ui_guessing_mappings = False
```

Hope this helps.
At any rate, this add-on is very useful, and I'm glad it's open-source.
