### ISSUE TITLE
Location Value gets lost

### ISSUE THREAD

**Issue by Kite2810** [Mwni/blender-animation-retargeting#38]
When you retarget an animation with this tool, the location value of the new animation doesn´t work. As example: You have a running animation and your character goes up and down while running. The retarget animation just stands still in the air with his body, instead of going up and down. Looks like a life less running animation.

**Comment by Mwni** [comment]
That is intentional. You can bake the skeletal animation and then copy over the simple location animation of the object.

**Comment by Kite2810** [comment]
Well yeah that doesn´t work. I tried already for weeks to copy over the location. But it always ends up pretty weird. I even tried manually copying over every single value for each keyframe, with no success. idk why just not a single tool for retargeting the location value keeps. Am I missing something? I don´t even know what "bake" means in that way. 

Don´t mean to bother or something. I just don´t understand why no one keeps the location value, since it is really important for me.

**Comment by Mwni** [comment]
Are you talking about the root bone location?

**Comment by Kite2810** [comment]
no no, the root bone just moves fine, in terms of location. I meant more other bones or atleast for me bone48, which is my hip bone. Since only one Bones location gets retarget too and the other don´t the animation looks mähh. If I set bone48 as root bone, then the location value for my hip is there, but not for my actual root bone.

**Comment by Mwni** [comment]
The offset locations of other bones do get retargeted as well. But I assume you are trying to retarget vastly different skeletons. Can I see your setup (Screenshot/Screencap)?

**Comment by Kite2810** [comment]
![image](https://github.com/user-attachments/assets/e12b5228-5505-4256-9326-df88f74a6351)
here. The bones are from 0 - 52 the EXACT same. I just added 6 bones to the model. In the screenshot, the one without wings is the original animation I try to retarget. 
He is swinging left and right for his attacks. The retarget animation don´t, since he lacks the location values. 
![image](https://github.com/user-attachments/assets/adf87ac2-572c-409e-951a-785337676e2b)

**Comment by Mwni** [comment]
I don't see how that's not working. The location of the hip bone is copied over in world space, or is it not?

**Comment by Kite2810** [comment]
it´s not. I think It would be better to make a video or such. Or the location of that is just VERY VERY small for some reason. Not completely sure. The dark grey one in the screenshot is the original. And the other one stands just there, but moves a few pixels when I ran the animation. So there is definitely location from the bones it seems.

**Comment by Mwni** [comment]
What's the object scale transform of both armatures? It could be that the addon handles locations incorrectly when target/source are scaled...

**Comment by Kite2810** [comment]
They have the exact same scale. How I exported them and maked them. ALL the same scaling, same bones. Except like I said the 6 bones for the wings. If it helps. I tried using Blender 3.0 and 4.1. 
[Wing Blade.zip](https://github.com/user-attachments/files/17264565/Wing.Blade.zip)
I added my Model and the animation. Maybe, just MAYBE I´m the problem. Maybe I understand something wrong. But if you´re interested in that, to try it out for yourself. I think that should help. 

Kind regards :)

**Comment by Mwni** [comment]
Yeah the issue is definitely scale. Both armatures had scale 0.010, if you clear the scale keyframes on the source armature and scale both to 1, it works. Regardless, this is a bug and shall be fixed eventually. Thx for sending it in.
![ee9e6e59c8](https://github.com/user-attachments/assets/dd321a56-90f8-4dfd-8f87-046857267fba)

**Comment by Mwni** [comment]
Fixed by https://github.com/Mwni/blender-animation-retargeting/commit/a015a7fe4e78051a7a402a5383563ab8fc2cb079

**Comment by Kite2810** [comment]
Ahhh I see! Thank god it was really a bug, Thanks for fixing it!
