### ISSUE TITLE
addon not functioning, blender version compatibility? 

### ISSUE THREAD

**Issue by UnleashedGH** [Mwni/blender-animation-retargeting#8]
i'm currently using Blender (2.8.0), i was able to install the addon, set bone mappings, then Save and Load configs correctly

however when trying to setup the rest pose, the "apply" button doesn't show up
![image](https://user-images.githubusercontent.com/47185022/86593751-7a8cb080-bf9e-11ea-9cb4-4a56a5c3e503.png)

i inspected the addons source code looking for the issue, i found out that (2.8.0) doesn't like "CHECKMARK" as an operator icon
so i replaced it with "X" as a workaround 
![image](https://user-images.githubusercontent.com/47185022/86593916-c8a1b400-bf9e-11ea-9e9d-3a12957cfa9e.png)

now the Apply button shows up, but upon clicking it... nothing happens
it pretty much feels like clicking on "Cancel"
once again i inspected the Apply code, and its pretty much exactly the same as the "Cancel" code with an additional call to "store_matrices()"
![image](https://user-images.githubusercontent.com/47185022/86594059-0999c880-bf9f-11ea-80fc-315752df2b36.png)

but.... shouldn't there be more code? something like start_drivers() or something? (i haven't looked at all the source)
i'm quite confused on what happens next, since the addon's README states that : "The add-on will then automatically create drivers for each bone, and you should be good to go."

**Comment by Mwni** [comment]
`leave_edit` actually calls `state.update_drivers()` which does the expected thing. As to why it has no effect in your case, could it be that you actually didn't change any of the rest pose? try just changing the pose of a single bone ever so slightly. I know it's a design flaw, but if the aligned pose is identical to the rest pose, the addon assumes you have not set one, yet.

**Comment by UnleashedGH** [comment]
> `leave_edit` actually calls `state.update_drivers()` which does the expected thing. As to why it has no effect in your case, could it be that you actually didn't change any of the rest pose? try just changing the pose of a single bone ever so slightly. I know it's a design flaw, but if the aligned pose is identical to the rest pose, the addon assumes you have not set one, yet.

the 2 armatures in my scene are identical (so is the rest pose), but one of them has different bone orientation  
![image](https://user-images.githubusercontent.com/47185022/86705896-ffb7aa00-c01e-11ea-9839-fb2240e54298.png)

as another workaround, i removed the **s.get_alignments_count() > 0** condition from **update_drivers**
although now i'm receiving an error 

> drivers.py in line 136, in create_vars 
> var.targets[0].rotation_mode = 'QUATERNION'
> 
> AttributeError : 'DriverTarget' object has no attribute 'rotation_mode'

i'm suspecting this to be another compatibility issue, although i've taken a look at the Blender 2.80 Pyton API and objects do have a "rotation_mode" Attribute 
https://docs.blender.org/api/2.80/bpy.types.Object.html?highlight=rotation_mode#bpy.types.Object.rotation_mode

so i'm again confused here, could this be because of me removing the alignment check?

**Comment by Mwni** [comment]
I too am confused. Removing that check should not cause the rotation mode to be missing. It could however be, that the targets `s_source` and `mapping_source` are not defined and that fails to set rotation mode therefor.

Again, applying any changes to the alignment pose did not work? Also are you bound to 2.80, if you could try it with a newer version, this would determine it being a compatibility issue.

**Comment by UnleashedGH** [comment]
> I too am confused. Removing that check should not cause the rotation mode to be missing. It could however be, that the targets `s_source` and `mapping_source` are not defined and that fails to set rotation mode therefor.
> 
> Again, applying any changes to the alignment pose did not work? Also are you bound to 2.80, if you could try it with a newer version, this would determine it being a compatibility issue.

i did try changing the alignment pose, but that yielded the same error

i've tried the addon with the latest version of blender (2.83.2 as of this date) and it worked with no issues
i also tried removing the alignment check again to see if that would cause anything, but the addon still worked fine regardless.

so it seems its incompatible with 2.80... weird
that could be a bug with the 2.80 Python API itself

**Comment by Mwni** [comment]
Closing as 2.8 support is no longer in the scope. Reopen if you still need assistance.
