### ISSUE TITLE
Corrects seem to clear / reset the rest of the rig?

### ISSUE THREAD

**Issue by joshcamas** [Mwni/blender-animation-retargeting#9]
Hello! First off, thank you so much for building this addon. It's incredible seeing a retargetting tool finally come back to blender.

I'm having an issue with corrections - both hands and feet. Once I enable it (and set both hand+upper arm bones), the pose seems to reset, clearing all drivers on the whole rig. Strangely the arms seem to somewhat be animated, even without drivers. I'm guessing that has to do with the hands correction strategy?

Regardless, odd bug. Is this a known issue? It's almost like it had an error and stopped halfway through, but there are no errors in the command window.

**Comment by Mwni** [comment]
>  It's almost like it had an error and stopped halfway through
That is exactly what it sound like to me aswell. This is not common, in fact the first time i heard of this.

I'd need something to troubleshoot, like a copy of the armatures used, or more details about your setup.
Are you using 1.81+?

**Comment by joshcamas** [comment]
I'm using 1.83. I realized I had a copy rotation bone constraint on the hand bone (it was disabled, but still it was there), and it looks like removing it somehow allowed some errors to print. Maybe it got a little bit further then still failed.

`ERROR (bke.anim_sys): C:\b\buildbot-worker-windows\windows_lts_283\blender.git\source\blender\blenkernel\intern\anim_sys.c:2815 BKE_animsys_eval_driver: invalid driver - pose.bones["lowerarm.l"].constraints["IK"].influence[0]
ERROR (bke.anim_sys): C:\b\buildbot-worker-windows\windows_lts_283\blender.git\source\blender\blenkernel\intern\anim_sys.c:2815 BKE_animsys_eval_driver: invalid driver - pose.bones["palm.r"].constraints["Copy Rotation"].influence[0]`

This is interesting. Both of these constraints (IK on lower arm, Copy Rotation on palm) were constraints I had but removed during testing to see if it would fix things. Is this a coincidence?

**Comment by Mwni** [comment]
These errors pop up even after you removed those two constraints?

**Comment by Mwni** [comment]
You know what I think is going on here, blender internally uses drivers to implement constraints, and my addon somehow pinned the internal drivers so they remain even if the constraint was removed. that is basically what the errors say, it tried to access the constraints properties, but the constraints are not there anymore.

Can you try the setup without constraints before applying the retargeting so we have a baseline?

**Comment by joshcamas** [comment]
Hmm, it looks like it's almost "corrupted". I'll have to start from a fresh rig.

**Comment by joshcamas** [comment]
Alright, it looks like this may be the case. I started from a fresh rig, removed the constraints, and then retargetted. Same issue, same errors.

Interestingly, when I removed the constraints, it threw the driver error once. Is this normal, or could this point towards a possible blender bug? ;o

**Comment by Mwni** [comment]
Yeah this is starting to look like a blender bug. The fact that the errors were thrown before the addon even had the chance to mess with it is evidence of that. One last thing you could try is restart blender without the addon, then do it again to see if really has nothing to do with it. Other than that i'd need a copy of the setup to know.

**Comment by joshcamas** [comment]
Yep, I disabled the addon and restarted blender, and it still throws the error. Pretty sure this means it's a blender bug. 
Here's my setup, the retarget config is included. As for the hand fixing bones, it'd be "upper_arm.l" and "palm.l".

Thank you so much for working so hard on helping me, it's beyond helpful.

https://drive.google.com/file/d/10J35pued_Unv4Kma_GfSizKVS6qMkx3C/view?usp=sharing

**Comment by Mwni** [comment]
So, luckily the only real problem was, that you had some of your bones marked as protected, and the addon bit its teeth out trying to modify the rotation mode of the bones. Just uncheck protection from all bone layers, and everything works. Will consider this case in the next patch.

On a side note, i see your model is having rather unexpected hip movement, if you have any ideas what to incorporate into the addon to help against such, feel free.

**Comment by Mwni** [comment]
About the last part, i just saw that your targets root bone was half a meter behind the back, moving it to the center of the hips in edit mode alleviated the strong hip sway.

**Comment by joshcamas** [comment]
Ah, I forgot I had removed that line of code that set the rotation, since there originally was a reason for those bones to be protected. However, even if I do indeed uncheck protection, it still doesn't work. (correct hands or feet position). Did you try correcting one of them, and it still worked?

**Comment by Mwni** [comment]
Yes, it all worked perfectly. I've mailed you the .blend.

**Comment by joshcamas** [comment]
This is very strange. I downloaded the blend, and am still having issues. When I enable "Correct Hands Position" and fill in the bones, the rest of the body stops animating, with just the arms animating.
![Screenshot_341](https://user-images.githubusercontent.com/26180637/88430401-40e4e380-cdad-11ea-8d8f-8ea75bcf3f88.png)
![Screenshot_342](https://user-images.githubusercontent.com/26180637/88430402-417d7a00-cdad-11ea-8795-0eb580ce7bdf.png)

Am I missing something?

**Comment by Mwni** [comment]
Can you try quickly turning 'Disable Drivers' on and off. It sometimes glitches directly after loading and doing that makes the addon rebuild all the drivers

**Comment by joshcamas** [comment]
Hm seems to not work. I'm using blender 2.83, and I tried removing all other addons. I suppose there's nothing that can be done if it can't be replicated on your end, very strange...

**Comment by Mwni** [comment]
You said
>When I enable "Correct Hands Position"
.. that option should have been enabled already in the file i sent you. you did use the .blend file i sent in the email attachment, right?

**Comment by joshcamas** [comment]
I did, although when I opened the blend file you sent me, it doesn't seem to load the state correctly, so I still had to load the config, apply alignment, and so on. Here's what it looks like when I open it:
![Screenshot_343](https://user-images.githubusercontent.com/26180637/88433425-e2baff00-cdb2-11ea-82bd-18451a42fd84.png)

**Comment by Mwni** [comment]
Ah, you see, the file you opened is still your old file. I didn't send you a google drive link, I replied to your google drive link with an actual email attachment and you must've mistaken that google drive link with the attachment. ;)

**Comment by joshcamas** [comment]
OH I finally downloaded the correct file. Alright, when I open it up, this is what I get: https://www.youtube.com/watch?v=N5MQKwfNMCY&feature=youtu.be

**Comment by Mwni** [comment]
Well, there's not much i can do anymore. We run the same version with the same setup and your system console prints no errors...

**Comment by joshcamas** [comment]
Yep, all I get is that blender driver error. Well, thank you so much for all of your dedication! Hopefully it'll magically fix itself somehow, clearly something is wonky on my end :)

**Comment by Mwni** [comment]
Maybe try to delete those faulty drivers on all bones that cause these errors:
![driver](https://user-images.githubusercontent.com/13929820/88437580-0b6ce400-ce07-11ea-8647-1e2c1601c2a9.png)
Other than that, good luck :D

**Comment by joshcamas** [comment]
Alright, I seemed to have found the problem. Somewhat. 
I decided to just copy my base rig file and apply everything, and it worked, without needing to delete my various bone constraints, and thus avoiding the odd driver brokenness errors.

The issue seemed to have stemmed from the fact that this rig that I was experimenting on was a linked proxy. I had unlinked it to see if that would fix it, and it didn't. It seems somehow if the armature was ever linked at one point, somehow that breaks it permanently. At least, on my machine. That has to be some sort of blender bug.

Thus, I guess I can't have a linked armature and use the tool. Darn! Regardless, as long as I avoid linking *at any point* when dealing with this tool it works perfectly! Thank you so much for your help, and the tool itself. It's a huge lifesaver.

**Comment by Mwni** [comment]
Good to hear! That also explains why it worked for me. Didn't even know linking armatures was a thing tbh. Anyways, it's on the list for the next patch. Take care.

**Comment by joshcamas** [comment]
Yep, the issue stems from when linking an armature and converting it into a proxy. Apparently blender is working on a new feature called "Library Overrides" which will replace proxies, perhaps when they implement it these issues will be solved on their end. :))
